# Generated by Django 5.2.4 on 2025-07-10 16:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código de categoría')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('campos_especificos', models.JSONField(blank=True, default=dict, help_text='Campos específicos para esta categoría en formato JSON', verbose_name='Campos específicos')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de marca')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del proveedor')),
                ('nif_cif', models.CharField(max_length=20, unique=True, verbose_name='NIF/CIF')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de ubicación')),
                ('edificio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Edificio')),
                ('planta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Planta')),
                ('sala', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sala/Oficina')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['edificio', 'planta', 'sala'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del departamento')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('dni', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}[A-Z]$', 'Formato DNI inválido')], verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email corporativo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('puesto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puesto de trabajo')),
                ('activo', models.BooleanField(default=True, verbose_name='Empleado activo')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Empleado Receptor',
                'verbose_name_plural': 'Empleados Receptores',
                'ordering': ['nombre'],
            },
        ),
    ]
