# Generated by Django 5.2.4 on 2025-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_usuario_creacion_departamento_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='campos_especificos',
        ),
        migrations.AddField(
            model_name='categoria',
            name='_campos_especificos',
            field=models.TextField(blank=True, default='{}', help_text='Campos específicos para esta categoría en formato JSON', verbose_name='Campos específicos'),
        ),
    ]
