# Generated by Django 5.2.4 on 2025-07-10 16:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('id_interno', models.CharField(help_text='Código único del producto generado automáticamente', max_length=20, unique=True, verbose_name='ID Interno')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de serie')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de barras')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ENTREGADO', 'Entregado'), ('AVERIADO', 'Averiado'), ('ROTO', 'Roto/Sin reparación'), ('RECOGIDO', 'Recogido'), ('BAJA', 'Dado de baja')], default='DISPONIBLE', max_length=20, verbose_name='Estado actual')),
                ('condicion', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO_BUENO', 'Usado - Buen estado'), ('USADO_REGULAR', 'Usado - Estado regular'), ('AVERIADO', 'Averiado'), ('OBSOLETO', 'Obsoleto')], default='NUEVO', max_length=20, verbose_name='Condición física')),
                ('fecha_compra', models.DateField(help_text='Fecha en que se adquirió el producto', verbose_name='Fecha de compra')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de compra (€)')),
                ('factura_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de factura')),
                ('fecha_fin_garantia', models.DateField(blank=True, null=True, verbose_name='Fecha fin de garantía')),
                ('especificaciones', models.JSONField(blank=True, default=dict, help_text='Especificaciones específicas según la categoría del producto', verbose_name='Especificaciones técnicas')),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='codigos_qr/', verbose_name='Código QR')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el producto', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Categoría')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca', verbose_name='Marca')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor', verbose_name='Proveedor')),
                ('ubicacion_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ubicacion', verbose_name='Ubicación actual')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['numero_serie'], name='productos_p_numero__66d67e_idx'), models.Index(fields=['estado'], name='productos_p_estado_ec69d1_idx'), models.Index(fields=['categoria'], name='productos_p_categor_17b5fc_idx')],
            },
        ),
    ]
