# Generated by Django 5.2.4 on 2025-07-11 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_usuario_creacion_departamento_descripcion_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PegatinasIdentificativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('tipo_pegatina', models.CharField(choices=[('QR', 'Código QR'), ('CODIGO_BARRAS', 'Código de barras'), ('ETIQUETA_SIMPLE', 'Etiqueta simple'), ('ETIQUETA_COMPLETA', 'Etiqueta completa')], max_length=20, verbose_name='Tipo de pegatina')),
                ('codigo_generado', models.CharField(max_length=200, verbose_name='Código generado')),
                ('imagen_pegatina', models.ImageField(blank=True, null=True, upload_to='pegatinas/', verbose_name='Imagen de la pegatina')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('impresa', models.BooleanField(default=False, verbose_name='Impresa')),
                ('fecha_impresion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de impresión')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pegatinas', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Pegatina Identificativa',
                'verbose_name_plural': 'Pegatinas Identificativas',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo')),
                ('codigo_prefijo', models.CharField(help_text='Prefijo para generar números de serie (ej: MV, ORD, TAB)', max_length=10, unique=True, verbose_name='Prefijo del código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('campos_personalizados', models.JSONField(default=dict, help_text='Configuración de campos específicos para este tipo de producto', verbose_name='Campos personalizados')),
                ('ultimo_numero', models.IntegerField(default=0, verbose_name='Último número generado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categorias', models.ManyToManyField(blank=True, help_text='Categorías que detectan automáticamente este tipo de producto', to='core.categoria', verbose_name='Categorías asociadas')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DatosPersonalizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('datos', models.JSONField(default=dict, help_text='Valores de los campos personalizados', verbose_name='Datos personalizados')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_personalizados', to='productos.producto', verbose_name='Producto')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto', verbose_name='Tipo de producto')),
            ],
            options={
                'verbose_name': 'Datos Personalizados',
                'verbose_name_plural': 'Datos Personalizados',
            },
        ),
    ]
