# Generated by Django 5.2.4 on 2025-07-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_pegatinasidentificativas_tipoproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='especificaciones',
            field=models.JSONField(blank=True, default=dict, help_text='Especificaciones específicas según la categoría del producto', null=True, verbose_name='Especificaciones técnicas'),
        ),
    ]
