# Generated by Django 5.2.4 on 2025-07-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_especificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='productos/', verbose_name='Imagen del producto'),
        ),
    ]
