# Generated by Django 5.2.4 on 2025-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_allow_null_numero_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonalizados',
            name='datos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='especificaciones',
        ),
        migrations.RemoveField(
            model_name='tipoproducto',
            name='campos_personalizados',
        ),
        migrations.AddField(
            model_name='datospersonalizados',
            name='_datos',
            field=models.TextField(default='{}', help_text='Valores de los campos personalizados', verbose_name='Datos personalizados'),
        ),
        migrations.AddField(
            model_name='producto',
            name='_especificaciones',
            field=models.TextField(blank=True, default='{}', help_text='Especificaciones específicas según la categoría del producto', null=True, verbose_name='Especificaciones técnicas'),
        ),
        migrations.AddField(
            model_name='tipoproducto',
            name='_campos_personalizados',
            field=models.TextField(default='{}', help_text='Configuración de campos específicos para este tipo de producto', verbose_name='Campos personalizados'),
        ),
    ]
