# Generated by Django 5.2.4 on 2025-07-10 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('tipo_movimiento', models.CharField(choices=[('ALTA', 'Alta de producto'), ('BAJA', 'Baja de producto'), ('TRANSFERENCIA', 'Transferencia de ubicación'), ('ACTUALIZACION', 'Actualización de datos'), ('REPARACION', 'Envío a reparación'), ('RETORNO_REPARACION', 'Retorno de reparación')], max_length=20, verbose_name='Tipo de movimiento')),
                ('ubicacion_origen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación origen')),
                ('ubicacion_destino', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación destino')),
                ('descripcion', models.TextField(verbose_name='Descripción del movimiento')),
                ('valor_anterior', models.JSONField(blank=True, default=dict, help_text='Para actualizaciones, guarda los valores previos', verbose_name='Valores anteriores')),
                ('valor_nuevo', models.JSONField(blank=True, default=dict, verbose_name='Valores nuevos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('tipo_asignacion', models.CharField(choices=[('ENTREGA', 'Entrega'), ('DEVOLUCION', 'Devolución'), ('REPARACION', 'Envío a reparación'), ('RETORNO_REPARACION', 'Retorno de reparación'), ('BAJA', 'Dar de baja'), ('PRESTAMO', 'Préstamo temporal'), ('FIN_PRESTAMO', 'Fin de préstamo')], max_length=20, verbose_name='Tipo de asignación')),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de entrega')),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de devolución')),
                ('fecha_prevista_devolucion', models.DateField(blank=True, help_text='Para préstamos temporales', null=True, verbose_name='Fecha prevista de devolución')),
                ('motivo_devolucion', models.CharField(blank=True, choices=[('CAMBIO_EMPLEADO', 'Cambio de empleado'), ('AVERIA', 'Producto averiado'), ('OBSOLETO', 'Producto obsoleto'), ('ACTUALIZACION', 'Actualización de equipo'), ('FIN_CONTRATO', 'Fin de contrato'), ('TRASLADO', 'Traslado de departamento'), ('ROBO_PERDIDA', 'Robo o pérdida'), ('OTROS', 'Otros motivos')], max_length=20, null=True, verbose_name='Motivo de devolución')),
                ('observaciones_entrega', models.TextField(blank=True, null=True, verbose_name='Observaciones en la entrega')),
                ('observaciones_devolucion', models.TextField(blank=True, null=True, verbose_name='Observaciones en la devolución')),
                ('documento_entrega', models.FileField(blank=True, help_text='Acta de entrega firmada o similar', null=True, upload_to='documentos_asignacion/', verbose_name='Documento de entrega')),
                ('documento_devolucion', models.FileField(blank=True, null=True, upload_to='documentos_asignacion/', verbose_name='Documento de devolución')),
                ('estado_producto_entrega', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO_BUENO', 'Usado - Buen estado'), ('USADO_REGULAR', 'Usado - Estado regular'), ('AVERIADO', 'Averiado'), ('OBSOLETO', 'Obsoleto')], max_length=20, verbose_name='Estado del producto en la entrega')),
                ('estado_producto_devolucion', models.CharField(blank=True, choices=[('NUEVO', 'Nuevo'), ('USADO_BUENO', 'Usado - Buen estado'), ('USADO_REGULAR', 'Usado - Estado regular'), ('AVERIADO', 'Averiado'), ('OBSOLETO', 'Obsoleto')], max_length=20, null=True, verbose_name='Estado del producto en la devolución')),
                ('confirmado_empleado', models.BooleanField(default=False, help_text='El empleado ha confirmado la recepción', verbose_name='Confirmado por empleado')),
                ('fecha_confirmacion_empleado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación del empleado')),
                ('activo', models.BooleanField(default=True, verbose_name='Registro activo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento', verbose_name='Departamento')),
                ('empleado_receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empleadoreceptor', verbose_name='Empleado receptor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('usuario_devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra la devolución')),
                ('usuario_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra la entrega')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Historial de Asignaciones',
                'ordering': ['-fecha_entrega'],
                'indexes': [models.Index(fields=['producto', 'fecha_entrega'], name='asignacione_product_9dffca_idx'), models.Index(fields=['empleado_receptor'], name='asignacione_emplead_1f0104_idx'), models.Index(fields=['departamento'], name='asignacione_departa_a6b890_idx'), models.Index(fields=['tipo_asignacion'], name='asignacione_tipo_as_4ca6f5_idx')],
            },
        ),
    ]
