# Generated by Django 5.2.4 on 2025-07-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientostock',
            name='valor_anterior',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='valor_nuevo',
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='_valor_anterior',
            field=models.TextField(blank=True, default='{}', help_text='Para actualizaciones, guarda los valores previos', verbose_name='Valores anteriores'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='_valor_nuevo',
            field=models.TextField(blank=True, default='{}', verbose_name='Valores nuevos'),
        ),
    ]
